---
title: "Loading and preprocessing of the CART data"
author: "Konstantinos Charitidis"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    toc: true
    toc_depth: '3'
    df_print: paged
  bookdown::html_document2:
    toc: true
    toc_depth: 3
    toc_float:
      collapse: false
    number_sections: true
    df_print: paged
    theme: readable
    code_folding: hide
    self_contained: true
    highlight: tango
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE)
options(max.print = 200)

```

```{r Libraries, include = FALSE}

library(tidyverse)
library(Seurat)
library(SeuratObject)
library(Matrix)
library(SingleR)
library(scRNAseq)

```

```{r Load the filtered seurat object}

SeO_1_filtered <- readRDS(file = "../Data/Edited_data/SeO_1_filtered_final.Rds")

```


```{r Get the specific slide}

SeO_1_filtered@meta.data %>% 
  select(Run_Tissue_name, slide_ID_numeric) %>% 
  filter(slide_ID_numeric == 2)

Se_by_slide <- SplitObject(SeO_1_filtered, split.by = "slide_ID_numeric")
SeO_CART <- Se_by_slide[["2"]]

```


```{r Normalise the seurat object counts}

SeO_CART_norm <- NormalizeData(SeO_CART, normalization.method = "LogNormalize",
                                scale.factor = 1e4)

SeO_CART_norm <- FindVariableFeatures(SeO_CART_norm, nfeatures = 3000)

SeO_CART_norm <- ScaleData(SeO_CART_norm, features = VariableFeatures(SeO_CART_norm))

SeO_CART_norm <- RunPCA(SeO_CART_norm, features = VariableFeatures(SeO_CART_norm))

ElbowPlot(SeO_CART_norm)

SeO_CART_norm <- RunUMAP(SeO_CART_norm, dims = 1:30)

DimPlot(SeO_CART_norm, reduction = "umap", group.by = "fov")

SeO_CART@meta.data$Cell_ID
# SaveSeuratRds(object = SeO_1_norm, file = "../Data/Edited_data/SeO_1_norm.Rds")

```

